language: node_js
node_js:
  - node

notifications:
  slack:
    secure: cvaxrTlmWR0DGrQR3iqLUPWtG6tWub0nd4X/3wgLSuRS+q6a5zWLHOJm+phv0Y+TkLCt3C1HT7iyLTKzCMb89hYqJMYZHPsyBBaIsN8ZPLWGl+aZfDerzvru+2hAsDvmR38tTiEhxY6uoCG2pLPCDW6uOyb0ZtdVdys41NjfIwIHeO7iNyGw3iz7cAWjSUdnhI22s5NzmObXoWzvgTXjREKFqrSzApzuE/8dYc8x5R+VHpu0HvSYtc8SyBa9FuCvBGGNPe6qEjC0PdI7aMT5hWNfLA+GMHM12fT4f2WXu1Ae1nUivYAzJqpeHvVnoEwl2NcVSJldoZw40x/x7A4QxXogsNEmRGVGoJHZv2ULkbiBm/+IIn+ebz9da9O+3vt6h8QmJEB/Y4ebvhThW549Jep1xMPjrtePQXn800NNSNK5sQH/ibWC5Tvdqgvh+kVCddyOwGmdAsmGo0eeAAxbDrYrQgaLl609mVe4DNHFsZdOWZAM+tskT+PgtJsqSE+ZHUJTbEypMgQj191IYuYtrz9HnQeEqvj8YG4htFzxn0K2INxjSQw7W685Bbi6tnCLdnhgFYux6OrlepckPiAg9Ox06TXujUwvRzdyv3g1svWcCObP0S/eEXiLkemBaq5AdRjmbGw2SzEY+eVcz9IQOw4eX7QaANcB0g8yEXMPHM8=
    exclude:
      if: (fork = true)

install:
  - npm install
  - npm install -g codecov

script:
  - npm run test

after_success:
  - codecov
